#+OPTIONS: tags:nil toc:nil author:nil num:nil H:3
#+LATEX_HEADER: \usepackage[profilePic={photo},profilePicWidth=60pt]{myCV}
#+latex_header: \usepackage[T2A]{fontenc}
#+OPTIONS: tags:t tasks:t tex:t timestamp:t toc:nil todo:t |:t
#+OPTIONS: author:nil c:nil creator:comment d:(not "LOGBOOK") date:nil
#+OPTIONS: e:t email:nil f:t inline:t num:t p:nil pri:nil stat:t

#+TITLE: Дробин Максим
* Контакты
** Почта
[[mailto:drobin.me@yandex.ru][drobin.me@yandex.ru]]

** тел(+ телеграм/whatapp): +79772774261
* Языки
Английский - Upper-intermediate
* Опыт работы
** Июнь 2018 - ноябрь 2018. Инженер-программист в Модульбанке
- Строил модели для расчета LTV
- С помощью Python автоматически выкачивал данные из внешней БД(mixpanel) в локальную БД
- Участвовал в проектировании схем в БД
- Занимался автоматизацией бизнес процессов в маркетинге: сделал скрипт, который автоматически обновлял информацию в маркетинговых кабинетах(AdWords, яндекс аудитории, My Target) из БД
- Занимался автоматизацией маркетинговой кампании по тригерам почтовой рассылки(Emarsys): письмо дошло/не дошло, адресант его открыл или нет, прошел ли по рекламной ссылке
- Участвовал в обсуждение бизнес процессов
** Июль 2019 - сентябрь 2019. ml-инженер в Тинькофф банке
- исправил геоматчинг и названия торговых точек на официальные, понятные, на русском языке в транзакциях. До этого названия магазина было обозначено через транслитерацию. Иногда это было не название торговой точки, а название юридического лица. Еще, координатой многих магазинов в Москве был обозначен центр Москвы. Исправил их на координаты самих магазинов.
** Сентябрь 2019 - ...
Ведущий курса antisoft skills в МФТИ по развитию личностных навыков под супервизией Марии Тиуновой - нарративного практика. 
* Образование
** МФТИ (ГУ) (2015 – 2019)
ПМФ, ФРТК, кафедра - ЦИТИС

Бакалавр, тема ВКР
# Тема ВКР
#+BEGIN_CENTER
*/Прогнозирование температуры во времени и пространстве/*
#+END_CENTER
* Навыки
** Отраслевые
Машинное обучение, программирование, алгоритмы, анализ данных, математика, статистика
** Иниструменты и технологии
Python, SQL, Linux, Emacs, Git
** Коммуникабельность
- Был ведущим психологического курса "Антидеконструкторское бюро: навык, которые определяешь ты сам" на физтехе.
Давал примеры заданий, работал в парах и тройках, создавал атмосферу на занятии
- Участвовал в паре хакатонов, делал совместные учебные проекты, участвовал в соревнание на kaggle в команде
** Другие
Pytorch, NumPy, requests, deep learning, unit testing

* EXTRA-CURRICULAR ACTIVITIES
** Март 2018 – Май 2018
Хакатон/соревнование от Модульбанка на booster.pro, Хакатон проходил в 2 этапа. 1й - на сайте booster.pro,
шел 2 месяца - нужно было построить модель классификации по анонимизированным данным(попал в топ 25%). 2й - более творческий 
этап. Он проходил 2 дня. По дополнительным данным нужно было предложить свое творческое решение, которое может принести бизнессу
прибыль. Мы построили ансамбль из алгоритмов, которые в некотором приближении давал систему рекомендации. Заняли номинацию "За лучший код"!

** Декабрь 2017
Хакатон в МФТИ от global changers, командный хакатон. Задача была от Сибура - найти во временном ряду аномалии. 
Аномалии размечены не были. Заняли 2е место
** Апрель 2018 - май 2018
[[https://boosters.pro/championship/modulbank1][Modulbank AI Hack MSK (boosters)]] - топ 25%
** Декабрь 2018 - Январь 2019
Telecom Data Cup (ml bootcamp) - топ 50%
** Февраль 2019 - апрель 2019
okko competition по рекомендательным системам на [[http://\boosters.pro][boosters]] - топ6
* Курсы
** Февраль 2017 - июнь 2017
- Курс по Java от NetCracker
** Сентябрь 2017 – Май 2018
- Парадигмы бизнесс программирования - курс от Никс по SQL
** September 2017 – Декабрь 2017
- DMIA - курс по машинному обучению от яндекса
** Инюнь 2017 – Ноябрь 2017
- 2 первых курса по специализации машинного обучения от Янлекса и МФТИ, coursera
** Февраль 2019 - Май 2019
- курс от mail ru по deep learning
- первые 3 курса по deep learning от Andrew NG

* Ссылки
** github
[[https://github.com/gazon1/][gazon1]]
** boosters
[[https://boosters.pro/user/Malahai][Malahai]]
** kaggle
[[https://www.kaggle.com/malahai][malahai]]
