#+OPTIONS: tags:nil toc:nil author:nil num:nil H:3
#+LATEX_HEADER: \usepackage[profilePic={photo},profilePicWidth=60pt]{myCV}
#+latex_header: \usepackage[T2A]{fontenc}
#+OPTIONS: tags:t tasks:t tex:t timestamp:t toc:nil todo:t |:t
#+OPTIONS: author:nil c:nil creator:comment d:(not "LOGBOOK") date:nil
#+OPTIONS: e:t email:nil f:t inline:t num:t p:nil pri:nil stat:t

#+TITLE: Дробин Максим
* Контакты
[[https://www.facebook.com/profile.php?id=100042101110525][Facebook]], [[https://www.linkedin.com/in/maxim-drobin-a11b05154/][Linkedin]]
** Почта
[[mailto:drobin.me@yandex.ru][drobin.me@yandex.ru]]

** тел(+ телеграм/whatapp): +7-977-277-42-61
** Другое
[[https://www.kaggle.com/malahai][Kaggle]]
[[https://github.com/gazon1/][Github]]
[[https://boosters.pro/user/Malahai][Boosters]]
* Опыт работы
** Июнь 2018 - ноябрь 2018. Инженер-программист в Модульбанке
Автоматизировал бизнес процессы в маркетинге: 
- Автоматическое обновление лидов в БД по расписанию
- Автоматический запуск почтовых рекламных кампаний на новых лидах по тригеру
- Передача новых лидов на обзвон через скрипт
  
~Стект технологий:~
Python3, SQL, emarsys API, mytarget API, google marketing API
** Февраль 2019 - ... Ведущий soft skills в МФТИ
- Ведущий курса antisoft skills в МФТИ по развитию личностных навыков под супервизией нарративных практиков
- Организовал и провёл курс по нарративной практике для студентов волонтеров из проекта "Мне не все равно"
[[https://www.youtube.com/watch?v=EDkDUp0PgPE&list=PL7GczH8KmOkD5QFvkeFVhJj6aGqpHkmeL&index=12&t=0s][Мое выступление на край-фесте 6-7 июня 2020г по этому курсу]]
** Июль 2019 - сентябрь 2019. Junior data scientist в Тинькофф банке
- исправил геоматчинг и названия торговых точек на официальные, понятные, на русском языке в транзакциях. До этого названия магазина было обозначено через транслитерацию. Иногда это было не название торговой точки, а название юридического лица. Еще, координатой многих магазинов в Москве был обозначен центр Москвы. Исправил их на координаты самих магазинов.
  
~Cтек технологий:~ python, NER, SQL, hive, greenplum, zepellin, bash, python, keras, linux
** Октябрь 2019 - ... Собственный проект
"[[https://docs.google.com/presentation/d/1AiwyzLKDgDXIaclUwoyGgT-VDJMtJYJQqAMVfbNlB40/edit#slide=id.p1][HighCar]]"
Backend developer & PR manager
Работа над своим проектом - каршеринг электромобилей в Ереване.
- В апреле 2020 участвовали в преакселераторе МФТИ "инженер 4.0", где провел анализ рынка и конкурентов
- Разрабатал backened часть на django
- Подготовил [[https://docs.google.com/presentation/d/1AiwyzLKDgDXIaclUwoyGgT-VDJMtJYJQqAMVfbNlB40/edit#slide=id.p1][elevator-pitch]] и выступил на нескольких elevator-pitch перед инвесторами
* Образование
** МФТИ (ГУ) (2015 – 2019)
ПМФ, ФРТК, кафедра - ЦИТИС

Бакалавр, тема ВКР
# Тема ВКР
#+BEGIN_CENTER
*/Прогнозирование температуры во времени и пространстве/*
#+END_CENTER
** МФТИ (ГУ) (2019 - 2021)
ПМФ, ФРТК, кафедра - ЦИТИС

Магистр, тема ВКР
#+BEGIN_CENTER
*/Применение ансамблей алгоритмов в Рекомендательной системе/*
#+END_CENTER

* Навыки
** Иниструменты и технологии
Python, SQL, Linux, Emacs, Git, bash
** Коммуникабельность
- Провёл сентябрь 2019 - апрель 2020 курс по soft skills в МФТИ, учился год 2019-2020 на психолога, поэтому смогу общаться с клиентом на его
языке и укреплять командный дух в компании и своей команде. Давал примеры заданий, работал в парах и тройках, создавал атмосферу на занятии
** Другие
- Pytorch, NumPy, pandas, xgboost, sklearn, fasttext, pickle, scipy, nltk, regex, tqdm, django, pycharm, requests, deep learning, unit testing
* It проекты, в которых участвовал                                 :noexport:
** Выпускная квалификационная работа в бакалавриате "Прогнозирование температуры во времени и пространства"
 https://github.com/gazon1/diplom-bachelor. Автоматизировал сбор данных с метеорологических станций по API через python3 и библиотеку requests. Обучил нейросеть на keras и ансамбль деревье по методу градиентного бустинга и сравнил качество прогноза для городов вблизи Лондона.
 
** Прототип навигации в колекции видео Постнауки методом тематического моделирования 
https://github.com/gazon1/post-nauka-project/blob/master/PostnaukaPeerReview.ipynb

** Классификатор по предсказанию категории обьявления по цене, описанию, заголовку
Итоговое решение - стекинг FastText классификатора и xgboost
https://github.com/gazon1/testing-task-Avito

** Sentiment analysis of movie review. Django
Приложение на django. Оно состоит из одной формы - в него можно написать
отзыв на фильм на англ и посмотреть тональность отзыва. Тональность предсказывается
Bert модель.
https://github.com/gazon1/GreenAtom

* Kaggle Deep Learning/ML Competitions
** Top 52% - [[https://cups.mail.ru/results/41?period=past&round_id=430][Telecom Data Cup (all cups mail ru)]]
** Топ 25% - [[https://boosters.pro/championship/modulbank1][Modulbank AI Hack MSK (boosters)]] 
** Топ 6% - [[https://boosters.pro/championship/rekko_challenge/overview][REKKO CHALLENGE (boosters)]]
https://github.com/gazon1/Recco-challenge

** Топ 13% - [[https://www.kaggle.com/c/competitive-data-science-predict-future-sales][Predict Future Sales (kaggle)]]
https://github.com/gazon1/1c

** Топ 68% - [[https://www.kaggle.com/c/2019s-neuralnet-track][Нейронные сети. ДЗ 1.]]
** Топ 40% - [[https://www.kaggle.com/c/nn-track-2019-spring-hw2][Нейронные сети. ДЗ 2.]]
** Топ 59%- [[https://www.kaggle.com/c/neuralnetworkshomework4/leaderboard][Neural Networks Homework 4 (ResNet)]]
** Топ 80% - [[https://www.kaggle.com/c/ieee-fraud-detection][IEEE-CIS Fraud Detection]]
** Топ 81% - [[https://www.kaggle.com/c/champs-scalar-coupling][Predicting Molecular Properties]]
* Волонтерство
** Зимний лагерь в Бельско-Устьенском детском доме интернате для детей с особенностями развития
- Помог провести за смену около 14 занятий с детьми в Бельско-Устьенском детском доме интернате для детей с особенностями развития. Всего смена длилась около недели
- Проводил чайные церемонии для волонтеров

  
