#+OPTIONS: tags:nil toc:nil author:nil num:nil H:3
#+LATEX_HEADER: \usepackage[profilePic={photo},profilePicWidth=60pt]{myCV}
#+latex_header: \usepackage[T2A]{fontenc}
#+OPTIONS: tags:t tasks:t tex:t timestamp:t toc:nil todo:t |:t
#+OPTIONS: author:nil c:nil creator:nil d:(not "LOGBOOK") date:nil
#+OPTIONS: e:t email:nil f:t inline:t num:t p:nil pri:nil stat:t

#+TITLE: Дробин Максим
* Контакты
[[https://www.facebook.com/profile.php?id=100042101110525][Facebook]], [[https://www.linkedin.com/in/maxim-drobin-a11b05154/][Linkedin]]
** Почта
[[mailto:drobin.me@yandex.ru][drobin.me@yandex.ru]]

** тел(+ телеграм/whatapp): +7-977-277-42-61
** Другое
- [[https://github.com/gazon1/gazon1.github.io/blob/master/README.org][Data science portfolio]]
- [[https://www.kaggle.com/malahai][Kaggle]] [[https://github.com/gazon1/][Github]] [[https://boosters.pro/user/Malahai][Boosters]] [[https://cups.mail.ru/profile/309773]["ML Boot Camp"]]
* Опыт работы
** Июнь 2018 - ноябрь 2018. Инженер-программист в Модульбанке
Автоматизировал бизнес процессы в маркетинге: 
- Автоматическое обновление лидов в БД по расписанию
- Автоматический запуск почтовых рекламных кампаний на новых лидах по тригеру
- Передача новых лидов на обзвон через скрипт
  
~Стект технологий:~
Python3, SQL, emarsys API, mytarget API, google marketing API
** Февраль 2019 - ... Ведущий soft skills в МФТИ
- Ведущий курса antisoft skills в МФТИ по развитию личностных навыков под супервизией нарративных практиков
- Организовал и провёл курс по нарративной практике для студентов волонтеров из проекта "Мне не все равно"
[[https://www.youtube.com/watch?v=EDkDUp0PgPE&list=PL7GczH8KmOkD5QFvkeFVhJj6aGqpHkmeL&index=12&t=0s][Мое выступление на край-фесте 6-7 июня 2020г по этому курсу]]
** Июль 2019 - сентябрь 2019. Junior data scientist в Тинькофф банке
- исправил геоматчинг и названия торговых точек на официальные, понятные, на русском языке в транзакциях. До этого названия магазина было обозначено через транслитерацию. Иногда это было не название торговой точки, а название юридического лица. Еще, координатой многих магазинов в Москве был обозначен центр Москвы. Исправил их на координаты самих магазинов.
  
~Cтек технологий:~ python, NER, SQL, hive, greenplum, zepellin, bash, python, keras, linux
** Октябрь 2019 - ... Собственный проект
"[[https://docs.google.com/presentation/d/1AiwyzLKDgDXIaclUwoyGgT-VDJMtJYJQqAMVfbNlB40/edit#slide=id.p1][HighCar]]"
Backend developer & PR manager
Работа над своим проектом - каршеринг электромобилей в Ереване.
- В апреле 2020 участвовали в преакселераторе МФТИ "инженер 4.0", где провел анализ рынка и конкурентов
- Разрабатал backened часть на django
- Подготовил [[https://docs.google.com/presentation/d/1AiwyzLKDgDXIaclUwoyGgT-VDJMtJYJQqAMVfbNlB40/edit#slide=id.p1][elevator-pitch]] и выступил на нескольких elevator-pitch перед инвесторами
* Образование
** МФТИ (ГУ) (2015 – 2019)
ПМФ, ФРТК, кафедра - ЦИТИС

Бакалавр, тема ВКР
# Тема ВКР
#+BEGIN_CENTER
*/Прогнозирование температуры во времени и пространстве/*
#+END_CENTER
** МФТИ (ГУ) (2019 - 2021)
ПМФ, ФРТК, кафедра - ЦИТИС

Магистр, тема ВКР
#+BEGIN_CENTER
*/Применение ансамблей алгоритмов в Рекомендательной системе/*
#+END_CENTER

* Навыки                                                           :noexport:
** Иниструменты и технологии
Python, SQL, Linux, Emacs, Git, bash
** Коммуникабельность
- Провёл сентябрь 2019 - апрель 2020 курс по soft skills в МФТИ, учился год 2019-2020 на психолога, поэтому смогу общаться с клиентом на его
языке и укреплять командный дух в компании и своей команде. Давал примеры заданий, работал в парах и тройках, создавал атмосферу на занятии
** Другие
- Pytorch, NumPy, pandas, xgboost, sklearn, fasttext, pickle, scipy, nltk, regex, tqdm, django, pycharm, requests, deep learning, unit testing
* Kaggle Deep Learning/ML Competitions
** Top 52% - Telecom Data Cup (ML Boot Camp)
** Топ 25% - Modulbank AI Hack MSK (boosters)
** Топ 6% - REKKO CHALLENGE (boosters)
** Топ 13% - Predict Future Sales (kaggle)
** Топ 68% - [[https://www.kaggle.com/c/2019s-neuralnet-track][Нейронные сети. ДЗ 1.]]
** Топ 40% - [[https://www.kaggle.com/c/nn-track-2019-spring-hw2][Нейронные сети. ДЗ 2.]]
** Топ 59% - Neural Networks Homework 4 (ResNet)
** Топ 80% - IEEE-CIS Fraud Detection
** Топ 81% - Predicting Molecular Properties
** Топ 81% - Cleaned vs Dirty V2
* It проекты, в которых участвовал
** [[http://167.172.97.243:8000/map/][Project city rate]]
~Проблема.~ В больших городах разные районы и даже микро-районы отличаются по благоустройству, качеству инфраструктуры, развитости
транспорта, экологии и другим параметрам. И при выборе места жительства хочется знать, насколько в нём всё хорошо или плохо. На глаз выбрать
место, где жить, сделать сложно. Стандартные ГИС-сервисы (гугл, яндекс, 2гис..) больше заточены под поиск конкретного места по названию или по категориям. Если же нужна некоторая статистика в локальной области (скажем, 1 км) вокруг интересующей вас точки, руками её собирать не очень удобно. Да и если собрали, непонятно, с чем сравнивать.

~Идея проекта.~
Создать что-то вроде индекса привлекательности места жительства по ряду критериев и красиво визуализировать это дело на картах, чтобы помочь людям принимать более взвешенное решение при выборе места для покупки / аренды жилья.
** "[[https://docs.google.com/presentation/d/1AiwyzLKDgDXIaclUwoyGgT-VDJMtJYJQqAMVfbNlB40/edit#slide=id.p1][HighCar]]"
** [[https://docs.google.com/presentation/d/1yi3B47CxyzGHnKza1snK03tzrlmESLaszM7MK1unRtk/edit#slide=id.p][Рекомендательная система чая для компании Мойчай.ру]]
* Волонтерство
** Зимний лагерь в Бельско-Устьенском детском доме интернате для детей с особенностями развития
- Помог провести за смену около 14 занятий с детьми в Бельско-Устьенском детском доме интернате для детей с особенностями развития. Всего смена длилась около недели
- Проводил чайные церемонии для волонтеров

  
